#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.WebserviceData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Servicios")]
	public partial class DataServiceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTBL_GS_USUARIO(TBL_GS_USUARIO instance);
    partial void UpdateTBL_GS_USUARIO(TBL_GS_USUARIO instance);
    partial void DeleteTBL_GS_USUARIO(TBL_GS_USUARIO instance);
    #endregion
		
		public DataServiceDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ServiciosConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataServiceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataServiceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataServiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataServiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_GS_USUARIO> TBL_GS_USUARIO
		{
			get
			{
				return this.GetTable<TBL_GS_USUARIO>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_SeleccionarInformacionUsuario")]
		public ISingleResult<SP_SEG_SeleccionarInformacionUsuarioResult> SP_SEG_SeleccionarInformacionUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Correo_Electronico", DbType="VarChar(250)")] string p_Correo_Electronico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Contrasenna", DbType="VarChar(MAX)")] string p_Contrasenna)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_Correo_Electronico, p_Contrasenna);
			return ((ISingleResult<SP_SEG_SeleccionarInformacionUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_SeleccionarSeccionesPorRol")]
		public ISingleResult<SP_SEG_SeleccionarSeccionesPorRolResult> SP_SEG_SeleccionarSeccionesPorRol([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Rol", DbType="Int")] System.Nullable<int> p_Rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_Rol);
			return ((ISingleResult<SP_SEG_SeleccionarSeccionesPorRolResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_SeleccionarRol")]
		public ISingleResult<SP_SEG_SeleccionarRolResult> SP_SEG_SeleccionarRol()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_SEG_SeleccionarRolResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_InsertarRol")]
		public int SP_SEG_InsertarRol([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Descripcion", DbType="VarChar(50)")] string p_Descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Estado", DbType="Char(1)")] System.Nullable<char> p_Estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Usuario", DbType="VarChar(50)")] string p_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_Descripcion, p_Estado, p_Usuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_EditarRol")]
		public int SP_SEG_EditarRol([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_ID", DbType="Int")] System.Nullable<int> p_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Descripcion", DbType="VarChar(50)")] string p_Descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Estado", DbType="Char(1)")] System.Nullable<char> p_Estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Usuario", DbType="VarChar(50)")] string p_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_ID, p_Descripcion, p_Estado, p_Usuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_Seleccionar_Usuarios")]
		public ISingleResult<SP_SEG_Seleccionar_UsuariosResult> SP_SEG_Seleccionar_Usuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_SEG_Seleccionar_UsuariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_InsertarUsuario")]
		public int SP_SEG_InsertarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Usuario", DbType="VarChar(50)")] string p_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Contrasenna", DbType="VarChar(MAX)")] string p_Contrasenna, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Nombre", DbType="VarChar(50)")] string p_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Correo", DbType="VarChar(250)")] string p_Correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Telefono", DbType="VarChar(10)")] string p_Telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Estado", DbType="Char(1)")] System.Nullable<char> p_Estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Rol", DbType="Int")] System.Nullable<int> p_Rol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_UsuarioCreacion", DbType="VarChar(50)")] string p_UsuarioCreacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_UsuarioModificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_Usuario, p_Contrasenna, p_Nombre, p_Correo, p_Telefono, p_Estado, p_Rol, p_UsuarioCreacion, p_UsuarioModificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_SeleccionarMenuPorRol")]
		public ISingleResult<SP_SEG_SeleccionarMenuPorRolResult> SP_SEG_SeleccionarMenuPorRol([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Rol", DbType="Int")] System.Nullable<int> p_Rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_Rol);
			return ((ISingleResult<SP_SEG_SeleccionarMenuPorRolResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_Seleccionar_Menus")]
		public ISingleResult<SP_SEG_Seleccionar_MenusResult> SP_SEG_Seleccionar_Menus()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_SEG_Seleccionar_MenusResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_Seleccionar_Permiso_Por_Rol_Y_Menu")]
		public ISingleResult<SP_SEG_Seleccionar_Permiso_Por_Rol_Y_MenuResult> SP_SEG_Seleccionar_Permiso_Por_Rol_Y_Menu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_IdMenu", DbType="Int")] System.Nullable<int> p_IdMenu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_IdRol", DbType="Int")] System.Nullable<int> p_IdRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Estado", DbType="Char(1)")] System.Nullable<char> p_Estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_IdMenu, p_IdRol, p_Estado);
			return ((ISingleResult<SP_SEG_Seleccionar_Permiso_Por_Rol_Y_MenuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_Actualizar_Lista_Permisos")]
		public int SP_SEG_Actualizar_Lista_Permisos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Estado", DbType="Char(1)")] System.Nullable<char> p_Estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_ID", DbType="Int")] System.Nullable<int> p_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Usuario_Modificacion", DbType="VarChar(50)")] string p_Usuario_Modificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Fecha_Modificacion", DbType="Date")] System.Nullable<System.DateTime> p_Fecha_Modificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_Estado, p_ID, p_Usuario_Modificacion, p_Fecha_Modificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_Seleccionar_Permiso_Por_Rol")]
		public ISingleResult<SP_SEG_Seleccionar_Permiso_Por_RolResult> SP_SEG_Seleccionar_Permiso_Por_Rol([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_ROL", DbType="Int")] System.Nullable<int> p_ROL)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_ROL);
			return ((ISingleResult<SP_SEG_Seleccionar_Permiso_Por_RolResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ADM_Seleccionar_Tareas_Estandar")]
		public ISingleResult<SP_ADM_Seleccionar_Tareas_EstandarResult> SP_ADM_Seleccionar_Tareas_Estandar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ADM_Seleccionar_Tareas_EstandarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ADM_Insertar_Tarea_Estandar")]
		public int SP_ADM_Insertar_Tarea_Estandar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Descripcion", DbType="VarChar(50)")] string p_Descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Estado", DbType="Char(1)")] System.Nullable<char> p_Estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Usuario", DbType="VarChar(50)")] string p_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_Descripcion, p_Estado, p_Usuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ADM_Editar_Tarea_Estandar")]
		public int SP_ADM_Editar_Tarea_Estandar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_ID", DbType="Int")] System.Nullable<int> p_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Descripcion", DbType="VarChar(50)")] string p_Descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Estado", DbType="Char(1)")] System.Nullable<char> p_Estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Usuario", DbType="VarChar(50)")] string p_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_ID, p_Descripcion, p_Estado, p_Usuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEG_EditarUsuario")]
		public int SP_SEG_EditarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_ID", DbType="Int")] System.Nullable<int> p_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Usuario", DbType="VarChar(50)")] string p_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Contrasenna", DbType="VarChar(MAX)")] string p_Contrasenna, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Nombre", DbType="VarChar(50)")] string p_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Correo", DbType="VarChar(250)")] string p_Correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Telefono", DbType="VarChar(10)")] string p_Telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Estado", DbType="Char(1)")] System.Nullable<char> p_Estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_Rol", DbType="Int")] System.Nullable<int> p_Rol, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_UsuarioModificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_ID, p_Usuario, p_Contrasenna, p_Nombre, p_Correo, p_Telefono, p_Estado, p_Rol, p_UsuarioModificacion);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_GS_USUARIO")]
	public partial class TBL_GS_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Usuario;
		
		private string _Contrasenna;
		
		private string _Nombre;
		
		private string _Correo_Electronico;
		
		private string _Telefono;
		
		private char _Estado;
		
		private int _Rol;
		
		private string _Usuario_Creacion;
		
		private string _Usuario_Modificacion;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion;
		
		private System.Nullable<System.DateTime> _Fecha_Modificacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContrasennaChanging(string value);
    partial void OnContrasennaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCorreo_ElectronicoChanging(string value);
    partial void OnCorreo_ElectronicoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnEstadoChanging(char value);
    partial void OnEstadoChanged();
    partial void OnRolChanging(int value);
    partial void OnRolChanged();
    partial void OnUsuario_CreacionChanging(string value);
    partial void OnUsuario_CreacionChanged();
    partial void OnUsuario_ModificacionChanging(string value);
    partial void OnUsuario_ModificacionChanged();
    partial void OnFecha_CreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_CreacionChanged();
    partial void OnFecha_ModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_ModificacionChanged();
    #endregion
		
		public TBL_GS_USUARIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenna", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Contrasenna
		{
			get
			{
				return this._Contrasenna;
			}
			set
			{
				if ((this._Contrasenna != value))
				{
					this.OnContrasennaChanging(value);
					this.SendPropertyChanging();
					this._Contrasenna = value;
					this.SendPropertyChanged("Contrasenna");
					this.OnContrasennaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_Electronico", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Correo_Electronico
		{
			get
			{
				return this._Correo_Electronico;
			}
			set
			{
				if ((this._Correo_Electronico != value))
				{
					this.OnCorreo_ElectronicoChanging(value);
					this.SendPropertyChanging();
					this._Correo_Electronico = value;
					this.SendPropertyChanged("Correo_Electronico");
					this.OnCorreo_ElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="Int NOT NULL")]
		public int Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Creacion", DbType="VarChar(50)")]
		public string Usuario_Creacion
		{
			get
			{
				return this._Usuario_Creacion;
			}
			set
			{
				if ((this._Usuario_Creacion != value))
				{
					this.OnUsuario_CreacionChanging(value);
					this.SendPropertyChanging();
					this._Usuario_Creacion = value;
					this.SendPropertyChanged("Usuario_Creacion");
					this.OnUsuario_CreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Modificacion", DbType="VarChar(50)")]
		public string Usuario_Modificacion
		{
			get
			{
				return this._Usuario_Modificacion;
			}
			set
			{
				if ((this._Usuario_Modificacion != value))
				{
					this.OnUsuario_ModificacionChanging(value);
					this.SendPropertyChanging();
					this._Usuario_Modificacion = value;
					this.SendPropertyChanged("Usuario_Modificacion");
					this.OnUsuario_ModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion
		{
			get
			{
				return this._Fecha_Creacion;
			}
			set
			{
				if ((this._Fecha_Creacion != value))
				{
					this.OnFecha_CreacionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Creacion = value;
					this.SendPropertyChanged("Fecha_Creacion");
					this.OnFecha_CreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Modificacion
		{
			get
			{
				return this._Fecha_Modificacion;
			}
			set
			{
				if ((this._Fecha_Modificacion != value))
				{
					this.OnFecha_ModificacionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Modificacion = value;
					this.SendPropertyChanged("Fecha_Modificacion");
					this.OnFecha_ModificacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_SEG_SeleccionarInformacionUsuarioResult
	{
		
		private int _ID;
		
		private string _Usuario;
		
		private string _Contrasenna;
		
		private string _Nombre;
		
		private string _Correo_Electronico;
		
		private string _Telefono;
		
		private char _Estado;
		
		private int _Rol;
		
		private string _Usuario_Creacion;
		
		private string _Usuario_Modificacion;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion;
		
		private System.Nullable<System.DateTime> _Fecha_Modificacion;
		
		public SP_SEG_SeleccionarInformacionUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenna", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Contrasenna
		{
			get
			{
				return this._Contrasenna;
			}
			set
			{
				if ((this._Contrasenna != value))
				{
					this._Contrasenna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_Electronico", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Correo_Electronico
		{
			get
			{
				return this._Correo_Electronico;
			}
			set
			{
				if ((this._Correo_Electronico != value))
				{
					this._Correo_Electronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="Int NOT NULL")]
		public int Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Creacion", DbType="VarChar(50)")]
		public string Usuario_Creacion
		{
			get
			{
				return this._Usuario_Creacion;
			}
			set
			{
				if ((this._Usuario_Creacion != value))
				{
					this._Usuario_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Modificacion", DbType="VarChar(50)")]
		public string Usuario_Modificacion
		{
			get
			{
				return this._Usuario_Modificacion;
			}
			set
			{
				if ((this._Usuario_Modificacion != value))
				{
					this._Usuario_Modificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion
		{
			get
			{
				return this._Fecha_Creacion;
			}
			set
			{
				if ((this._Fecha_Creacion != value))
				{
					this._Fecha_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Modificacion
		{
			get
			{
				return this._Fecha_Modificacion;
			}
			set
			{
				if ((this._Fecha_Modificacion != value))
				{
					this._Fecha_Modificacion = value;
				}
			}
		}
	}
	
	public partial class SP_SEG_SeleccionarSeccionesPorRolResult
	{
		
		private int _ID_Seccion;
		
		private int _ID_Rol;
		
		private char _Estado;
		
		private string _Usuario_Creacion;
		
		private string _Usuario_Modificacion;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion;
		
		private System.Nullable<System.DateTime> _Fecha_Modificacion;
		
		public SP_SEG_SeleccionarSeccionesPorRolResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Seccion", DbType="Int NOT NULL")]
		public int ID_Seccion
		{
			get
			{
				return this._ID_Seccion;
			}
			set
			{
				if ((this._ID_Seccion != value))
				{
					this._ID_Seccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Rol", DbType="Int NOT NULL")]
		public int ID_Rol
		{
			get
			{
				return this._ID_Rol;
			}
			set
			{
				if ((this._ID_Rol != value))
				{
					this._ID_Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Creacion", DbType="VarChar(50)")]
		public string Usuario_Creacion
		{
			get
			{
				return this._Usuario_Creacion;
			}
			set
			{
				if ((this._Usuario_Creacion != value))
				{
					this._Usuario_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Modificacion", DbType="VarChar(50)")]
		public string Usuario_Modificacion
		{
			get
			{
				return this._Usuario_Modificacion;
			}
			set
			{
				if ((this._Usuario_Modificacion != value))
				{
					this._Usuario_Modificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion
		{
			get
			{
				return this._Fecha_Creacion;
			}
			set
			{
				if ((this._Fecha_Creacion != value))
				{
					this._Fecha_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Modificacion
		{
			get
			{
				return this._Fecha_Modificacion;
			}
			set
			{
				if ((this._Fecha_Modificacion != value))
				{
					this._Fecha_Modificacion = value;
				}
			}
		}
	}
	
	public partial class SP_SEG_SeleccionarRolResult
	{
		
		private int _ID;
		
		private string _Descripcion;
		
		private char _Estado;
		
		private string _Usuario_Creacion;
		
		private string _Usuario_Modificacion;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion;
		
		private System.Nullable<System.DateTime> _Fecha_Modificacion;
		
		public SP_SEG_SeleccionarRolResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Creacion", DbType="VarChar(50)")]
		public string Usuario_Creacion
		{
			get
			{
				return this._Usuario_Creacion;
			}
			set
			{
				if ((this._Usuario_Creacion != value))
				{
					this._Usuario_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Modificacion", DbType="VarChar(50)")]
		public string Usuario_Modificacion
		{
			get
			{
				return this._Usuario_Modificacion;
			}
			set
			{
				if ((this._Usuario_Modificacion != value))
				{
					this._Usuario_Modificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion
		{
			get
			{
				return this._Fecha_Creacion;
			}
			set
			{
				if ((this._Fecha_Creacion != value))
				{
					this._Fecha_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Modificacion
		{
			get
			{
				return this._Fecha_Modificacion;
			}
			set
			{
				if ((this._Fecha_Modificacion != value))
				{
					this._Fecha_Modificacion = value;
				}
			}
		}
	}
	
	public partial class SP_SEG_Seleccionar_UsuariosResult
	{
		
		private int _ID;
		
		private string _Usuario;
		
		private string _Contrasenna;
		
		private string _Nombre;
		
		private string _Correo_Electronico;
		
		private string _Telefono;
		
		private char _Estado;
		
		private int _Rol;
		
		private string _Usuario_Creacion;
		
		private string _Usuario_Modificacion;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion;
		
		private System.Nullable<System.DateTime> _Fecha_Modificacion;
		
		public SP_SEG_Seleccionar_UsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenna", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Contrasenna
		{
			get
			{
				return this._Contrasenna;
			}
			set
			{
				if ((this._Contrasenna != value))
				{
					this._Contrasenna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_Electronico", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Correo_Electronico
		{
			get
			{
				return this._Correo_Electronico;
			}
			set
			{
				if ((this._Correo_Electronico != value))
				{
					this._Correo_Electronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="Int NOT NULL")]
		public int Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Creacion", DbType="VarChar(50)")]
		public string Usuario_Creacion
		{
			get
			{
				return this._Usuario_Creacion;
			}
			set
			{
				if ((this._Usuario_Creacion != value))
				{
					this._Usuario_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Modificacion", DbType="VarChar(50)")]
		public string Usuario_Modificacion
		{
			get
			{
				return this._Usuario_Modificacion;
			}
			set
			{
				if ((this._Usuario_Modificacion != value))
				{
					this._Usuario_Modificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion
		{
			get
			{
				return this._Fecha_Creacion;
			}
			set
			{
				if ((this._Fecha_Creacion != value))
				{
					this._Fecha_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Modificacion
		{
			get
			{
				return this._Fecha_Modificacion;
			}
			set
			{
				if ((this._Fecha_Modificacion != value))
				{
					this._Fecha_Modificacion = value;
				}
			}
		}
	}
	
	public partial class SP_SEG_SeleccionarMenuPorRolResult
	{
		
		private int _ID;
		
		private string _Descripcion;
		
		private char _Estado;
		
		private string _Usuario_Creacion;
		
		private string _Usuario_Modificacion;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion;
		
		private System.Nullable<System.DateTime> _Fecha_Modificacion;
		
		public SP_SEG_SeleccionarMenuPorRolResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Creacion", DbType="VarChar(50)")]
		public string Usuario_Creacion
		{
			get
			{
				return this._Usuario_Creacion;
			}
			set
			{
				if ((this._Usuario_Creacion != value))
				{
					this._Usuario_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Modificacion", DbType="VarChar(50)")]
		public string Usuario_Modificacion
		{
			get
			{
				return this._Usuario_Modificacion;
			}
			set
			{
				if ((this._Usuario_Modificacion != value))
				{
					this._Usuario_Modificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion
		{
			get
			{
				return this._Fecha_Creacion;
			}
			set
			{
				if ((this._Fecha_Creacion != value))
				{
					this._Fecha_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Modificacion
		{
			get
			{
				return this._Fecha_Modificacion;
			}
			set
			{
				if ((this._Fecha_Modificacion != value))
				{
					this._Fecha_Modificacion = value;
				}
			}
		}
	}
	
	public partial class SP_SEG_Seleccionar_MenusResult
	{
		
		private int _ID;
		
		private string _Descripcion;
		
		private char _Estado;
		
		private string _Usuario_Creacion;
		
		private string _Usuario_Modificacion;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion;
		
		private System.Nullable<System.DateTime> _Fecha_Modificacion;
		
		public SP_SEG_Seleccionar_MenusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Creacion", DbType="VarChar(50)")]
		public string Usuario_Creacion
		{
			get
			{
				return this._Usuario_Creacion;
			}
			set
			{
				if ((this._Usuario_Creacion != value))
				{
					this._Usuario_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Modificacion", DbType="VarChar(50)")]
		public string Usuario_Modificacion
		{
			get
			{
				return this._Usuario_Modificacion;
			}
			set
			{
				if ((this._Usuario_Modificacion != value))
				{
					this._Usuario_Modificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion
		{
			get
			{
				return this._Fecha_Creacion;
			}
			set
			{
				if ((this._Fecha_Creacion != value))
				{
					this._Fecha_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Modificacion
		{
			get
			{
				return this._Fecha_Modificacion;
			}
			set
			{
				if ((this._Fecha_Modificacion != value))
				{
					this._Fecha_Modificacion = value;
				}
			}
		}
	}
	
	public partial class SP_SEG_Seleccionar_Permiso_Por_Rol_Y_MenuResult
	{
		
		private int _ID;
		
		private string _Descripcion;
		
		private int _ID_Seccion;
		
		private int _ID_Rol;
		
		private int _ID_Menu;
		
		private char _Estado;
		
		private string _Usuario_Creacion;
		
		private string _Usuario_Modificacion;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion;
		
		private System.Nullable<System.DateTime> _Fecha_Modificacion;
		
		public SP_SEG_Seleccionar_Permiso_Por_Rol_Y_MenuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Seccion", DbType="Int NOT NULL")]
		public int ID_Seccion
		{
			get
			{
				return this._ID_Seccion;
			}
			set
			{
				if ((this._ID_Seccion != value))
				{
					this._ID_Seccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Rol", DbType="Int NOT NULL")]
		public int ID_Rol
		{
			get
			{
				return this._ID_Rol;
			}
			set
			{
				if ((this._ID_Rol != value))
				{
					this._ID_Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL")]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this._ID_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Creacion", DbType="VarChar(50)")]
		public string Usuario_Creacion
		{
			get
			{
				return this._Usuario_Creacion;
			}
			set
			{
				if ((this._Usuario_Creacion != value))
				{
					this._Usuario_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Modificacion", DbType="VarChar(50)")]
		public string Usuario_Modificacion
		{
			get
			{
				return this._Usuario_Modificacion;
			}
			set
			{
				if ((this._Usuario_Modificacion != value))
				{
					this._Usuario_Modificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion
		{
			get
			{
				return this._Fecha_Creacion;
			}
			set
			{
				if ((this._Fecha_Creacion != value))
				{
					this._Fecha_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Modificacion
		{
			get
			{
				return this._Fecha_Modificacion;
			}
			set
			{
				if ((this._Fecha_Modificacion != value))
				{
					this._Fecha_Modificacion = value;
				}
			}
		}
	}
	
	public partial class SP_SEG_Seleccionar_Permiso_Por_RolResult
	{
		
		private int _ID;
		
		private string _Descripcion;
		
		private int _ID_Menu;
		
		private int _ID_Seccion;
		
		private int _ID_Rol;
		
		private char _Estado;
		
		public SP_SEG_Seleccionar_Permiso_Por_RolResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL")]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this._ID_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Seccion", DbType="Int NOT NULL")]
		public int ID_Seccion
		{
			get
			{
				return this._ID_Seccion;
			}
			set
			{
				if ((this._ID_Seccion != value))
				{
					this._ID_Seccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Rol", DbType="Int NOT NULL")]
		public int ID_Rol
		{
			get
			{
				return this._ID_Rol;
			}
			set
			{
				if ((this._ID_Rol != value))
				{
					this._ID_Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SP_ADM_Seleccionar_Tareas_EstandarResult
	{
		
		private int _ID;
		
		private string _Descripcion;
		
		private char _Estado;
		
		private string _Usuario_Creacion;
		
		private string _Usuario_Modificacion;
		
		private System.Nullable<System.DateTime> _Fecha_Creacion;
		
		private System.Nullable<System.DateTime> _Fecha_Modificacion;
		
		public SP_ADM_Seleccionar_Tareas_EstandarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Creacion", DbType="VarChar(50)")]
		public string Usuario_Creacion
		{
			get
			{
				return this._Usuario_Creacion;
			}
			set
			{
				if ((this._Usuario_Creacion != value))
				{
					this._Usuario_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_Modificacion", DbType="VarChar(50)")]
		public string Usuario_Modificacion
		{
			get
			{
				return this._Usuario_Modificacion;
			}
			set
			{
				if ((this._Usuario_Modificacion != value))
				{
					this._Usuario_Modificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Creacion
		{
			get
			{
				return this._Fecha_Creacion;
			}
			set
			{
				if ((this._Fecha_Creacion != value))
				{
					this._Fecha_Creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Modificacion
		{
			get
			{
				return this._Fecha_Modificacion;
			}
			set
			{
				if ((this._Fecha_Modificacion != value))
				{
					this._Fecha_Modificacion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
