<?xml version="1.0" encoding="utf-8"?><Database Name="JazzCashier" Class="DataServiceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.9.24;Initial Catalog=JazzCashier;User ID=rsegura" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="JazzCashierConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbInternalUsers" Member="tbInternalUsers">
    <Type Name="tbInternalUser">
      <Column Name="IdUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserEmail" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="UsrPasw" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserCompleteName" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PaswExpired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>